[project]
name = "zblocks"
version = "0.1.0"
description = "z/OS Control Blocks Web Utility"
requires-python = ">=3.13"
dependencies = [
    "cffi>=1.17.1",
    "flask>=3.0.0",
    "python-dotenv",
    "networkx",
]
